# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoodwatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hood_name', models.CharField(max_length=25)),
                ('hood_location', models.CharField(max_length=50)),
                ('occupants_count', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Profile',
            new_name='Admin',
        ),
        migrations.AddField(
            model_name='hood',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hoodwatch.Admin'),
        ),
    ]
