# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoodwatch', '0004_business_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=25)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameField(
            model_name='business',
            old_name='email',
            new_name='business_email',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='name',
            new_name='business_name',
        ),
        migrations.RenameField(
            model_name='hood',
            old_name='location',
            new_name='hood_location',
        ),
        migrations.RenameField(
            model_name='hood',
            old_name='name',
            new_name='hood_name',
        ),
        migrations.AlterField(
            model_name='business',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='hoodwatch.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='hood_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoodwatch.Hood'),
        ),
    ]
