# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodwatch', '0004_hood_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hood',
            old_name='count',
            new_name='hood_count',
        ),
        migrations.RemoveField(
            model_name='hood',
            name='city',
        ),
    ]
