# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodwatch', '0005_auto_20181018_1223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Profile',
        ),
        migrations.RenameField(
            model_name='hood',
            old_name='admin',
            new_name='profile',
        ),
    ]
