# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodwatch', '0005_auto_20181021_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hood',
            name='hood_location',
            field=models.CharField(choices=[('Westlands', 'Nairobi'), ('Dagoretti', 'Nairobi'), ('Langata', 'Nairobi'), ('Kasarani', 'Nairobi'), ('Embakasi', 'Nairobi'), ('Starehe', 'Nairobi'), ('Kamkunji', 'Nairobi')], max_length=25),
        ),
    ]
