# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodwatch', '0006_auto_20181018_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(max_length=500),
        ),
    ]
