# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('hoodwatch', '0007_auto_20181018_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hood',
            options={'ordering': ('hood_name',)},
        ),
        migrations.AddField(
            model_name='hood',
            name='city',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hood',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=True, max_length=63),
        ),
    ]
