# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodwatch', '0008_auto_20181019_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hood',
            options={},
        ),
        migrations.RemoveField(
            model_name='hood',
            name='hood_location',
        ),
        migrations.RemoveField(
            model_name='hood',
            name='hood_name',
        ),
        migrations.RemoveField(
            model_name='hood',
            name='occupants_count',
        ),
    ]
