# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 08:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hoodwatch', '0009_auto_20181019_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hood_id',
        ),
        migrations.AlterModelOptions(
            name='hood',
            options={'ordering': ('hood_name',)},
        ),
        migrations.RenameField(
            model_name='hood',
            old_name='location',
            new_name='hood_location',
        ),
        migrations.RemoveField(
            model_name='hood',
            name='profile',
        ),
        migrations.AddField(
            model_name='hood',
            name='hood_name',
            field=models.CharField(default=True, max_length=25),
        ),
        migrations.AddField(
            model_name='hood',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='business',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
