# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoodwatch', '0009_hood_hood_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='hood_id',
            new_name='hood',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='profile',
            name='hood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hoodwatch.Hood'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
