# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 05:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodwatch', '0010_auto_20181022_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='post',
        ),
    ]
