# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodwatch', '0010_auto_20181019_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hood',
            name='city',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='hood',
            name='hood_location',
            field=models.CharField(choices=[('Nairobi', 'Nairobi'), ('Kisumu', 'Kisumu'), ('Mombasa', 'Mombasa')], max_length=2),
        ),
        migrations.AlterField(
            model_name='hood',
            name='hood_name',
            field=models.CharField(max_length=25),
        ),
    ]
