# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 09:17
from __future__ import unicode_literals

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('hoodwatch', '0011_auto_20181019_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hood',
            name='hood_location',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
